### PR TITLE
Feature: Support archive file events via `archive#watch` and  archive network events

### PR DESCRIPTION
**Pull request by saimonmoore**
- Added support for DatArchive network/file events system.
- Updated docs
- Bumped version to 2.0.3
- No tests :( but I tested it ;)

Let me know if anything is missing

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
This looks great, thank you!

**Comment by RangerMauve** [comment]
Published 2.0.3! :D

**Comment by rjcorwin** [comment]
I'm not sure what's up, I get `archive.watch is not a function` when using `https://unpkg.com/dat-archive-web@2.0.3/bundle.js`.

**Comment by RangerMauve** [comment]
Oh shoot, I didn't re-build the bundle! I'll do that now.

**Comment by RangerMauve** [comment]
Try version 2.0.4

**Comment by rjcorwin** [comment]
Thank you @RangerMauve! My multiplayer Connect Four app got past that original issue I posted. I'm now hitting another issue now. I'll gather more info to try and figure out what's going on.

**Pull request merged**
